### ISSUE TITLE
Change pineapple recipe

### ISSUE THREAD

**Issue by Bastrabun** [Can202/minetest_icecream#3]
Most other recipes require the smallest unit of fruit available, like the melon ice does not require a whole melon, but a melon slice. The pineapple recipe requires a whole pineapple, while the smallest unit is a pineapple ring.

Could you please make the pineapple icecream require a pineapple ring instead of a whole pineapple? Like so:

```
--pineapple icecream
minetest.register_craft({
	output = "icecream:pineapple",
	recipe = {
		{"default:snow"},
		{"farming:pineapple_ring"},
		{"icecream:cone"},
	}
})
```

If you wish I could PR this small change

For my reference 2230

**Comment by Can202** [comment]
Ok, I'm going to correct this, and sorry for this huge delay
